#!/bin/bash
#SBATCH --time=0:15:00
#SBATCH -C TitanX
#SBATCH --gres=gpu:1

module load cuda80/toolkit
module load cuda80/blas
module load cuda80
module load cuDNN

echo -n 'Started: ' && date

head -n 1000000 output/gigaword.txt > output/gigaword.1m-sents.txt && \
        python3 -u prepare-lstm-wsd.py output/gigaword.1m-sents.txt && \
        python3 -u train-lstm-wsd.py --data_path output/gigaword.1m-sents --save_path output/lstm-wsd-small

echo -n 'Finished: ' && date
    