#!/bin/bash
#SBATCH --time 1:00:00
#SBATCH --partition gpu_short

module load cuda/8.0.61
module load cudnn/8.0-v6.0

echo -n 'Started: ' && date

preprocess_version="2017-11-02-a453bc1"

# Check inside for loop in case the version has changed. There can be
# a day between iterations.
base_dir=output/`python3 version.py`
mkdir $base_dir 
data_path=preprocessed-data/$preprocess_version/gigaword-for-lstm-wsd_01-pc
base_path=$base_dir/lstm-wsd-gigaword-test-small
echo "Running a test script. Log is written to $base_path.log"
python3 -u train-lstm-wsd.py --model small \
        --data_path $data_path --save_path $base_path > $base_path.log 2>&1

echo -n 'Finished: ' && date
