#!/bin/bash
#SBATCH --time=72:00:00
#SBATCH -C TitanX
#SBATCH --gres=gpu:1

module load cuda80/toolkit
module load cuda80/blas
module load cuda80
module load cuDNN

echo -n 'Started: ' && date

out_dir=output/`python3 version.py`
mkdir $out_dir
log_file=$out_dir/exp-hyperp-label-propagation_algo-$3_sim-$1_gamma-$2.log
echo "Log is written to $log_file"

python3 -u debug_lp.py --algo=$3 --sim=$1 --gamma=$2 2>&1 | tee $log_file 

echo -n 'Finished: ' && date
    