#!/bin/bash
#SBATCH --time=5-00:00:00

git reset --hard && \
    git checkout 149cde7 && python3 -u preprocess_gigaword.py && \
    git checkout f802d4d && ./deduplicate_gigaword.sh && \
    git checkout 9fd479f && python3 -u split_gigaword.py && \
    git checkout 7d764e7 && python3 -u vectorize_gigaword.py && \
    git checkout e200820 && python3 -u convert_mono2hdn.py
    git checkout f48a06c && python3 -u generate_hdn_datasets.py

git checkout -